version: "3.9"
services:
    mserver_1_17:
        build: .
        ports:
            - "25565:25565"
        volumes:
            - minecraftworld:/mserver/world
volumes:
    minecraftworld:
        external: true
